name: one_health_hospital_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  bloc: ^8.0.3
  bottom_navy_bar: ^6.0.0
  build_runner: ^2.1.11
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  custom_timer: ^0.1.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_neumorphic: ^3.2.0
  flutter_svg: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  http: ^0.13.4
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  line_icons: ^2.0.1
  lottie: ^1.3.0
  page_transition: ^2.0.5
  pin_code_fields: ^7.4.0
  shimmer: ^2.0.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  icons_launcher: ^1.2.1

  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: 'images/one_health_logo.png'
  ios: true
  android: true
flutter:

  uses-material-design: true

  assets:
    - images/
    - json/
